### ISSUE TITLE
how to use  jodconverter 3.0 in centos minimal 6.4 ,

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SneakyLaiji/jodconverter#113]
```
hi,

how to use 3.0 in centos minimal 6.4, 

1. scoffice service is runing. 
2. I can use 2.2.2 version , converter file to pdf. it is working. 
3. butn I use 3.0 , I don't know use it . 

4. I test inport common. is terminal：

     [root@localhost ~]# java -jar jodconverter/lib/jodconverter-core-3.0-beta-4.jar 123.docx 123.pdf

have error will show:

Exception in thread "main" java.lang.IllegalStateException: officeHome not set 
and could not be auto-detected
    at org.artofsolving.jodconverter.office.DefaultOfficeManagerConfiguration.buildOfficeManager(DefaultOfficeManagerConfiguration.java:163)
    at org.artofsolving.jodconverter.cli.Convert.main(Convert.java:111)

please help me. thank you. I am a chinese . my english is pool . 
I hope you can understand my mean.

thanks , tell me how to use it in terminal . . 

my e-mail: 66eagle@163.com   my english name : eagle



http://groups.google.com/group/jodconverter

eagle
```

Original issue reported on code.google.com by `eagle.tr...@gmail.com` on 16 Dec 2013 at 5:59

**Comment by GoogleCodeExporter** [comment]
```
Hello,

I create a Java program which will convert Excel Invoices to PDF format.
For this reason I use OpenOffice 3.4.1 (headless) with JODConverter.

OpenOffice converts from XLS to PDF well, but I have one issue:
when XLS file is setted to print the pages as A4 portrait – when i convert 
this file to pdf, then all data which is out of A4 bounds will be “sliced” 
and printed as another A4 portrait PDF page.

Unfortunately I need to maintaine the integrity of contained tables, but I 
don`t have the possibility to set up manually the right Page Size (for example 
to set it to A3 or to A2)- all need to be automatized.

So… my solution is to change “on the fly” the Page Size when OpenOffice 
converts XLS to PDF.
I was able to set on the fly the Paper Size to A3, but as result I have only 
the first worksheet resized. All another worksheets remained A4. Sad

Can you please tell me how I can apply page resizing to all pages in XLS when 
converting?
Thanks! 

```

Original comment by `eagle.tr...@gmail.com` on 14 Jan 2014 at 7:48
